captureDirectory: 'capturing'
completeDirectory: 'captured'
modelScanInterval: 300
debug: true
models:
  - 10272360 # XViciousLoveX
  - 9759444 # Geniva_
includeModels:
  - MODELNAMETOSTARTCAPTURING
excludeModels:
  - MODELNAMETOSTOPCAPTURING